### ISSUE TITLE
zlib error when using awspublish.gzip()

### ISSUE THREAD

**Issue by shantp** [pgherveou/gulp-awspublish#86]
Using v3.0.1, when trying to use awspublish.gzip() on my files I get this error:

```
zlib.js:166
    callback(null, buf);
    ^
TypeError: object is not a function
    at Gzip.onEnd (zlib.js:166:5)
    at Gzip.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
```

I installed gulp-awspublish@2.0.2 and the error is gone and my files gzip correctly.

**Comment by delta62** [comment]
I can also repro this. Works in 2.0.2, but throws the error in 3.0.1.

**Comment by pgherveou** [comment]
weird the tests are passing on the latest version
are the tests working for you? 
https://github.com/pgherveou/gulp-awspublish#testing

**Comment by shantp** [comment]
The way gzip is being used in the tests is not the same as the way it is shown in the README. Maybe that is my issue. Is the options object required? Should it be gzip.pipe() as shown in the tests?

**Comment by pgherveou** [comment]
nop its not required 
this is how I use it to publish our files
```js
  const jsOrCss = gulp
    .src('./build/*.+(js|css)', { base: './build' })
    .pipe(awspublish.gzip())
    .pipe(publisher.publish(headers))

```

**Comment by shantp** [comment]
OK, that's what my task looks like and I get the zlib error. The only difference is I don't restrict it to js and css.

**Comment by pgherveou** [comment]
the zipping might fail on certain files?

**Comment by delta62** [comment]
I see the error if I'm running in an old version of node.

No problems in 4.0.0, breaks with 0.10.26. I did not test 12.x.

[This repo](https://github.com/delta62/aws-gzip) reproduces the error.

**Comment by shantp** [comment]
This must be my error. I am on a 0.10 version of node.

**Comment by ajbrown** [comment]
Confirming that upgrading to a 4.X version solves this problem.

**Comment by pgherveou** [comment]
cool, maybe we should then add a note in the readme and update the node
version in package.json
